In [2]:
import pandas as pd

books = pd.read_csv("complete_data.csv")
books

,Title,description,authors,categories,image,previewLink,unique_values,tagged_description
0,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,Philip Nel,Biography & Autobiography,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,1,1 Philip Nel takes a fascinating look into the...
1,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,David R. Ray,Religion,http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,2,2 This resource includes twelve principles in ...
2,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,Veronica Haddon,Fiction,http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,3,3 Julia Thomas finds her life spinning out of ...
3,The Church of Christ: A Biblical Ecclesiology ...,In The Church of Christ: A Biblical Ecclesiolo...,Everett Ferguson,Religion,http://books.google.com/books/content?id=kVqRa...,http://books.google.nl/books?id=kVqRaiPlx88C&p...,4,4 In The Church of Christ: A Biblical Ecclesio...
4,Saint Hyacinth of Poland,The story for children 10 and up of St. Hyacin...,Mary Fabyan Windeatt,Biography & Autobiography,http://books.google.com/books/content?id=lmLqA...,http://books.google.nl/books?id=lmLqAAAACAAJ&d...,5,5 The story for children 10 and up of St. Hyac...
...,...,...,...,...,...,...,...,...
128103,Final things,Grace's father believes in science and builds ...,Jenny Offill,Fiction,http://books.google.com/books/content?id=UbSFB...,http://books.google.com/books?id=UbSFBAAAQBAJ&...,128104,128104 Grace's father believes in science and ...
128104,The Magic of the Soul: Applying Spiritual Powe...,"""The Magic of the Soul, Applying Spiritual Pow...",Patrick J. Harbula,"Body, Mind & Spirit",http://books.google.com/books/content?id=H1ELA...,http://books.google.com/books?id=H1ELAAAACAAJ&...,128105,"128105 ""The Magic of the Soul, Applying Spirit..."
128105,Autodesk Inventor 10 Essentials Plus,Autodesk Inventor 2017 Essentials Plus provide...,"Daniel Banach, Travis Jones",Computers,http://books.google.com/books/content?id=zxHRC...,http://books.google.com/books?id=zxHRCwAAQBAJ&...,128106,128106 Autodesk Inventor 2017 Essentials Plus ...
128106,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",Elvira Woodruff,Juvenile Fiction,http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,128107,"128107 During a school trip to Ellis Island, D..."
128107,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,Zadie Smith,Fiction,http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,128108,128108 Alex-Li Tandem sells autographs. His bu...

In [3]:
books["categories"].value_counts().reset_index()

                       categories  count
0                         Fiction  21615
1                         History   8485
2                        Religion   8458
3                Juvenile Fiction   6221
4       Biography & Autobiography   5856
...                           ...    ...
4286       Psychosexual disorders      1
4287       Audio-visual materials      1
4288          Information society      1
4289  Bakersfield Region (Calif.)      1
4290        Physical measurements      1

[4291 rows x 2 columns]

In [4]:
books["categories"].value_counts().reset_index().query("count > 50")

                   categories  count
0                     Fiction  21615
1                     History   8485
2                    Religion   8458
3            Juvenile Fiction   6221
4   Biography & Autobiography   5856
..                        ...    ...
60              Great Britain     70
61          African Americans     63
62          Adventure stories     61
63           American fiction     58
64                  Copyright     51

[65 rows x 2 columns]

In [9]:
category_mapping = {'Fiction' : "Fiction",
 'Juvenile Fiction': "Fiction",
 'Biography & Autobiography': "Nonfiction",
 'History': "Nonfiction",
 'Literary Criticism': "Nonfiction",
 'Philosophy': "Nonfiction",
 'Religion': "Nonfiction",
 'Comics & Graphic Novels': "Fiction",
 'Drama': "Fiction",
 'Juvenile Nonfiction': "Nonfiction",
 'Science': "Nonfiction",
 'Poetry': "Fiction",
 'Business & Economics': "Fiction",
 'Computers': "Fiction",
 'Social Science' : "Fiction",
 'Education': "Fiction",
 'Sports & Recreation': "Fiction",
 'Psychology': "Fiction",
 'True Crime': "Fiction",
 'Technology & Engineering': "Fiction",
}

books["simple_categories"] = books["categories"].map(category_mapping)

In [10]:
books

,Title,description,authors,categories,image,previewLink,unique_values,tagged_description,simple_categories
0,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,Philip Nel,Biography & Autobiography,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,1,1 Philip Nel takes a fascinating look into the...,Nonfiction
1,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,David R. Ray,Religion,http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,2,2 This resource includes twelve principles in ...,Nonfiction
2,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,Veronica Haddon,Fiction,http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,3,3 Julia Thomas finds her life spinning out of ...,Fiction
3,The Church of Christ: A Biblical Ecclesiology ...,In The Church of Christ: A Biblical Ecclesiolo...,Everett Ferguson,Religion,http://books.google.com/books/content?id=kVqRa...,http://books.google.nl/books?id=kVqRaiPlx88C&p...,4,4 In The Church of Christ: A Biblical Ecclesio...,Nonfiction
4,Saint Hyacinth of Poland,The story for children 10 and up of St. Hyacin...,Mary Fabyan Windeatt,Biography & Autobiography,http://books.google.com/books/content?id=lmLqA...,http://books.google.nl/books?id=lmLqAAAACAAJ&d...,5,5 The story for children 10 and up of St. Hyac...,Nonfiction
...,...,...,...,...,...,...,...,...,...
128103,Final things,Grace's father believes in science and builds ...,Jenny Offill,Fiction,http://books.google.com/books/content?id=UbSFB...,http://books.google.com/books?id=UbSFBAAAQBAJ&...,128104,128104 Grace's father believes in science and ...,Fiction
128104,The Magic of the Soul: Applying Spiritual Powe...,"""The Magic of the Soul, Applying Spiritual Pow...",Patrick J. Harbula,"Body, Mind & Spirit",http://books.google.com/books/content?id=H1ELA...,http://books.google.com/books?id=H1ELAAAACAAJ&...,128105,"128105 ""The Magic of the Soul, Applying Spirit...",NaN
128105,Autodesk Inventor 10 Essentials Plus,Autodesk Inventor 2017 Essentials Plus provide...,"Daniel Banach, Travis Jones",Computers,http://books.google.com/books/content?id=zxHRC...,http://books.google.com/books?id=zxHRCwAAQBAJ&...,128106,128106 Autodesk Inventor 2017 Essentials Plus ...,Fiction
128106,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",Elvira Woodruff,Juvenile Fiction,http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,128107,"128107 During a school trip to Ellis Island, D...",Fiction
128107,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,Zadie Smith,Fiction,http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,128108,128108 Alex-Li Tandem sells autographs. His bu...,Fiction

In [11]:
books[~(books["simple_categories"].isna())]

,Title,description,authors,categories,image,previewLink,unique_values,tagged_description,simple_categories
0,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,Philip Nel,Biography & Autobiography,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,1,1 Philip Nel takes a fascinating look into the...,Nonfiction
1,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,David R. Ray,Religion,http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,2,2 This resource includes twelve principles in ...,Nonfiction
2,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,Veronica Haddon,Fiction,http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,3,3 Julia Thomas finds her life spinning out of ...,Fiction
3,The Church of Christ: A Biblical Ecclesiology ...,In The Church of Christ: A Biblical Ecclesiolo...,Everett Ferguson,Religion,http://books.google.com/books/content?id=kVqRa...,http://books.google.nl/books?id=kVqRaiPlx88C&p...,4,4 In The Church of Christ: A Biblical Ecclesio...,Nonfiction
4,Saint Hyacinth of Poland,The story for children 10 and up of St. Hyacin...,Mary Fabyan Windeatt,Biography & Autobiography,http://books.google.com/books/content?id=lmLqA...,http://books.google.nl/books?id=lmLqAAAACAAJ&d...,5,5 The story for children 10 and up of St. Hyac...,Nonfiction
...,...,...,...,...,...,...,...,...,...
128101,Petit Connoisseur: Art,Introduces toddlers to the world of art with i...,Karen Salmansohn,Juvenile Nonfiction,http://books.google.com/books/content?id=MbSSO...,http://books.google.com/books?id=MbSSOiETn1kC&...,128102,128102 Introduces toddlers to the world of art...,Nonfiction
128103,Final things,Grace's father believes in science and builds ...,Jenny Offill,Fiction,http://books.google.com/books/content?id=UbSFB...,http://books.google.com/books?id=UbSFBAAAQBAJ&...,128104,128104 Grace's father believes in science and ...,Fiction
128105,Autodesk Inventor 10 Essentials Plus,Autodesk Inventor 2017 Essentials Plus provide...,"Daniel Banach, Travis Jones",Computers,http://books.google.com/books/content?id=zxHRC...,http://books.google.com/books?id=zxHRCwAAQBAJ&...,128106,128106 Autodesk Inventor 2017 Essentials Plus ...,Fiction
128106,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",Elvira Woodruff,Juvenile Fiction,http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,128107,"128107 During a school trip to Ellis Island, D...",Fiction
128107,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,Zadie Smith,Fiction,http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,128108,128108 Alex-Li Tandem sells autographs. His bu...,Fiction

In [12]:
from transformers import pipeline

fiction_categories = ["Fiction", "Nonfiction"]

pipe = pipeline("zero-shot-classification",
                model="facebook/bart-large-mnli",
                device="cpu")

WARNING:tensorflow:From C:\Users\Ayush\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

C:\Users\Ayush\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Ayush\.cache\huggingface\hub\models--facebook--bart-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu

In [13]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]

In [14]:
pipe(sequence, fiction_categories)

{'sequence': 'Julia Thomas finds her life spinning out of control after the death of her husband, Richard. Julia turns to her minister for comfort when she finds herself falling for him with a passion that is forbidden by the church. Heath Sparks is a man of God who is busy taking care of his quadriplegic wife who was seriously injured in a sever car accident. In an innocent effort to reach out to a lonely member of his church, Heath finds himself as the man and not the minister as Heath and Julia surrender their bodies to each other and face the wrath of God. Julia finds herself in over her head as she faces a deadly disease, the loss of her home and whispers about her wicked affair. Julia leaves the states offering her body as a living sacrifice in hopes of finding a cure while her heart remains thousands of miles away hoping to one day reunite with the man who holds it hostage.Whispers of the Wicked Saints is a once in a lifetime romance that is breath taking, defying all the rules of romance and bending the laws of love.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.5809065103530884, 0.419093519449234]}

In [15]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [16]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [17]:
from tqdm import tqdm

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|████████████████████████████████████████████████████████████████████████████████| 300/300 [07:44<00:00,  1.55s/it]

In [18]:
for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

100%|████████████████████████████████████████████████████████████████████████████████| 300/300 [06:39<00:00,  1.33s/it]

In [19]:
predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})
predictions_df

    actual_categories predicted_categories
0             Fiction              Fiction
1             Fiction           Nonfiction
2             Fiction              Fiction
3             Fiction           Nonfiction
4             Fiction           Nonfiction
..                ...                  ...
595        Nonfiction           Nonfiction
596        Nonfiction           Nonfiction
597        Nonfiction           Nonfiction
598        Nonfiction              Fiction
599        Nonfiction           Nonfiction

[600 rows x 2 columns]

In [20]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_categories"] == predictions_df["predicted_categories"], 1, 0)
)

predictions_df["correct_prediction"].sum() / len(predictions_df)

np.float64(0.6583333333333333)

In [21]:
uvs = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["unique_values", "description"]].reset_index(drop=True)

In [24]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    uvs += [missing_cats["unique_values"][i]]

  1%|▋                                                                          | 439/45403 [07:25<12:41:01,  1.02s/it]

KeyboardInterrupt:

In [32]:
while len(uvs) < len(predicted_cats):
    uvs.append(None)

In [33]:
print(len(uvs))
print(len(predicted_cats))

441
441

In [34]:
missing_predicted_df = pd.DataFrame({"unique_values": uvs, "predicted_categories": predicted_cats})

In [35]:
missing_predicted_df

     unique_values predicted_categories
0              7.0           Nonfiction
1             11.0           Nonfiction
2             12.0           Nonfiction
3             13.0           Nonfiction
4             14.0           Nonfiction
..             ...                  ...
436         1173.0           Nonfiction
437         1175.0           Nonfiction
438         1176.0           Nonfiction
439            NaN           Nonfiction
440            NaN           Nonfiction

[441 rows x 2 columns]

In [36]:
books = pd.merge(books, missing_predicted_df, on="unique_values", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns = ["predicted_categories"])

In [41]:
books

,Title,description,authors,categories,image,previewLink,unique_values,tagged_description,simple_categories
0,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,Philip Nel,Biography & Autobiography,http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,1,1 Philip Nel takes a fascinating look into the...,Nonfiction
1,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,David R. Ray,Religion,http://books.google.com/books/content?id=2tsDA...,http://books.google.nl/books?id=2tsDAAAACAAJ&d...,2,2 This resource includes twelve principles in ...,Nonfiction
2,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,Veronica Haddon,Fiction,http://books.google.com/books/content?id=aRSIg...,http://books.google.nl/books?id=aRSIgJlq6JwC&d...,3,3 Julia Thomas finds her life spinning out of ...,Fiction
3,The Church of Christ: A Biblical Ecclesiology ...,In The Church of Christ: A Biblical Ecclesiolo...,Everett Ferguson,Religion,http://books.google.com/books/content?id=kVqRa...,http://books.google.nl/books?id=kVqRaiPlx88C&p...,4,4 In The Church of Christ: A Biblical Ecclesio...,Nonfiction
4,Saint Hyacinth of Poland,The story for children 10 and up of St. Hyacin...,Mary Fabyan Windeatt,Biography & Autobiography,http://books.google.com/books/content?id=lmLqA...,http://books.google.nl/books?id=lmLqAAAACAAJ&d...,5,5 The story for children 10 and up of St. Hyac...,Nonfiction
...,...,...,...,...,...,...,...,...,...
128103,Final things,Grace's father believes in science and builds ...,Jenny Offill,Fiction,http://books.google.com/books/content?id=UbSFB...,http://books.google.com/books?id=UbSFBAAAQBAJ&...,128104,128104 Grace's father believes in science and ...,Fiction
128104,The Magic of the Soul: Applying Spiritual Powe...,"""The Magic of the Soul, Applying Spiritual Pow...",Patrick J. Harbula,"Body, Mind & Spirit",http://books.google.com/books/content?id=H1ELA...,http://books.google.com/books?id=H1ELAAAACAAJ&...,128105,"128105 ""The Magic of the Soul, Applying Spirit...",NaN
128105,Autodesk Inventor 10 Essentials Plus,Autodesk Inventor 2017 Essentials Plus provide...,"Daniel Banach, Travis Jones",Computers,http://books.google.com/books/content?id=zxHRC...,http://books.google.com/books?id=zxHRCwAAQBAJ&...,128106,128106 Autodesk Inventor 2017 Essentials Plus ...,Fiction
128106,The Orphan Of Ellis Island (Time Travel Advent...,"During a school trip to Ellis Island, Dominick...",Elvira Woodruff,Juvenile Fiction,http://books.google.com/books/content?id=J7M-N...,http://books.google.com/books?id=J7M-NwAACAAJ&...,128107,"128107 During a school trip to Ellis Island, D...",Fiction
128107,The Autograph Man,Alex-Li Tandem sells autographs. His business ...,Zadie Smith,Fiction,http://books.google.com/books/content?id=JM6YV...,http://books.google.com/books?id=JM6YVPx_clMC&...,128108,128108 Alex-Li Tandem sells autographs. His bu...,Fiction

In [42]:
books.to_csv("books_with_categories.csv", index=False)